import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

export function LanguageProvider({ children }) {

  const storedLanguage = localStorage.getItem("appLanguage") || "en";
  const [language, setLanguage] = useState(storedLanguage);

  useEffect(() => {
    localStorage.setItem("appLanguage", language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "id" : "en"));
  };

  const translations = {
    en: {
      home: "𝑯𝒐𝒎𝒆",
      navbarMenu: "𝑴𝒆𝒏𝒖",
      aboutHero: "𝑨𝒃𝒐𝒖𝒕",
      knowCoffee: "Get Your Coffee and Food Here",
      contact: "𝑪𝒐𝒏𝒕𝒂𝒄𝒕",
      navbarArticles: "𝑨𝒓𝒕𝒊𝒄𝒍𝒆", 
      readArticle: "Read Article",
      latestArticle: "𝐋𝐚𝐭𝐞𝐬𝐭 𝐀𝐫𝐭𝐢𝐜𝐥𝐞",
      writerArticle: "Author",
      videoTag: "Your Browser doesn't support the video tag.",
      readMoreArticle: "Read More",
      selectVariant: "Select Variant",
      chatWithUs: "Chat With Us",
      filterAll: "All Menu",
      searchMenu: "Search Menu...",
      readLessFooters: "Read Less",
      readMoreFooters: "Read More",
      priceRange: "Price Range",
      backToMenu: "Back to Menu",
      menuNotFound: "Menu Not Found",
      menuSortBy: "Sort By",
      menuFeatured: "Featured",
      menuCategories: "Categories",
      menuClearFilters: "Clear All Filters",
      menuApplyFilters: "Apply All Filters",
      menuNameAtoZ: "Name: A to Z",
      menuNameZtoA: "Name: Z to A",
      menuNotFoundDesc: "Sorry, we couldn't find the drinks & food you were looking for...",
      menuPriceLowToHigh: "Price: Low to High",
      menuPriceHighToLow: "Price: High to Low",
      viewDetails: "𝐎𝐫𝐝𝐞𝐫 𝐍𝐨𝐰",
      addToCart: "Add to Cart",
      coverMenuDetailTitle: "Menu Detail",
      menuDetailTitle: "Description",
      menuDetailQuantity: "Quantity",
      ourMenu : "Our Menu",
      clickMenu: "View Details",
      articHero: "Articles",
      seeMenuTitle: "Our Signature Menu",
      placeHolderOrderList: "Search by name or product...",
      seeMenuButton: "𝐕𝐢𝐞𝐰 𝐀𝐥𝐥 𝐎𝐮𝐫 𝐒𝐢𝐠𝐧𝐚𝐭𝐮𝐫𝐞 𝐌𝐞𝐧𝐮",
      articHeroDesc: "See Articles",
      footerTitle: "𝑲𝑶𝑯𝑰 𝑪𝒐𝒇𝒇𝒆é 幸",
      founderKohi: "Founder of Kohi Coffeè 幸",
      founderKohiDesc: "Hola👋, i'm a Founder of Kohi Coffeè 幸 with concept of Japan, i'm a Web Developer and a Digital Marketing for over 5 years in industry.",
      footerDesc: "Premium coffee that made from high-quality beans.",
      readMoreFooter: "that are carefully sourced and prepared. It can be made from single-origin beans or blends of beans from different regions. Premium coffee is often more expensive than other coffees.",
      footerShop: "Menu",
      footerAbout: "About Us",
      footerContact: "Contact",
      menuDetailDesc: "Please proceed to payment",
      currentTime: "Current Time In",
      relatedsArticles: "Related Articles",
      orderListviewInvoice: "View Invoices",
      backToArticles: "Back to Articles",
      shareArticles: "Share This Articles",
      quickLinks: "Quick Links",
      discoverDesc: "𝑫𝒊𝒔𝒄𝒐𝒗𝒆𝒓",
      discoversDescs: "𝑻𝒉𝒆 𝑷𝒓𝒐𝒄𝒆𝒔𝒔",
      coffeeTalkTitle: "𝑪𝒐𝒇𝒇𝒆𝒆 𝑪𝒖𝒍𝒕𝒖𝒓𝒆 𝑩𝒓𝒆𝒂𝒌𝒕𝒉𝒓𝒐𝒖𝒈𝒉 𝒊𝒏 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂!",
      coffeeTalkDesc: "Kohi Coffeé presents the concept and style of a Japanese coffee shop. We want to invite everyone from coffee lovers, those who like to hang out and want to be seen as coffee lovers, to those who are not coffee lovers to enjoy the new culture of drinking coffee that is fun.",
      coffeeTalkLoc: "Our District",
      testimoniTitle: "Our Testimonials",
      testimoniNext: "Next",
      partnerTitle: "Our Partners",
      fitTitle: "𝑾𝒉𝒂𝒕 𝑫𝒐 𝒀𝒐𝒖 𝑮𝒆𝒕 𝑭𝒓𝒐𝒎 𝑼𝒔?",
      customerService: "Customer Service",
      selectSize: "Size",
      selectStock: "Stock",
      orderListAddOrders: "Add Order",
      orderListcloseOrders: "Close Order",
      footerShippingInfo: "Order Info",
      footerReturns: "Advice",
      footerGuide: "Guide",
      privacyPolicy: "Privacy Policy",
      termsService: "Terms of Service",
      cookiePolicy: "Cookie Policy",
      articlesNotFound: "Articles not found",
      contactUs: "Contact Us",
      copyright: "All Rights Reserved",
      cart: "Cart",
      ArticleTitle: "𝐅𝐞𝐚𝐭𝐮𝐫𝐞𝐝 𝐀𝐫𝐭𝐢𝐜𝐥𝐞",
      explore: "Explore More",
      shopCart: "Shopping Cart",
      checkCart: "Checkout Your Cart",
      emptyCart: "Oops...Your Orders Cart is Empty",
      emptyCartDesc: "Please Grab Your Order now...",
      emptyCartOrder: "Empty All the Carts",
      proceedCart: "Proceed to Checkout",
      chatType: "Type your chat here...",
      continueShop: "Back To Menu",
      goCart: "Shopping Cart",
      orderListTitle: "Orders List",
      orderListInvoice: "View Invoice",
      orderListNoOrdersFound: "No orders found yet...",
      orders: "𝑶𝒓𝒅𝒆𝒓𝒔",
      orderSummary: "Total Order",   
      toggleLanguage: "Indonesian",
      discover: "Explore our collection of premium coffees and hand-picked delights, perfectly blended to deliver the ultimate in comfort and taste...",
      order: "𝐎𝐫𝐝𝐞𝐫 𝐍𝐨𝐰",
      orderListPostalCode: "Postal Code",
      orderListPaymentChannel: "Payment Channel",
      learnMore: "Learn More",
      newsletterTitle: "Join Our Newsletter",
      newsletterText: "Subscribe to get special offers, free giveaways, and updates",
      emailPlaceholder: "Enter your email",
      subscribe: "Subscribe",
      orderListPaymentMethod: "Payment Method",
      freeShipping: "Free Shipping",
      freeShippingDesc: "On orders over $10",
      comfortPlace: "Comfortable Place and Aesthetic",
      comfortPlaceDesc: "Served with the nuances of Bali's natural beauty",
      wifi: "Free Wifi",
      wifiDesc: "Sit and relax with friends or family while surfing the internet",
      securePayment: "Secure Payment",
      securePaymentDesc: "100% secure payment",
      price: "Affordable Price",
      priceDesc: "Our Coffee is not so expensive, it's suitable for anyone, go grab one",
      support24: "24/7 Support",
      orderListGetYourOrders: "Please get your orders",
      orderListNoOrdersFoundHere: "here",
      support24Desc: "Dedicated support",
      qualityProducts: "Quality Coffee",
      orderListDetails: "Details",
      orderListDelete: "Delete",
      qualityProductsDesc: "Handpicked from the best selection of coffee beans",
      qualityTools: "Quality Coffee Tools",
      qualityToolsDesc: "We provide the best for our customers, the best quality tools for our customers",
      beanTitle: "Premium Coffee Beans",
      orderListAddress: "Address",
      beanDesc: "Experience the finest selection of coffee beans from around the world.",
      brewTitle: "Brew Like a Pro",
      orderListPhone: "Phone Number",
      brewDesc:"Learn the art of coffee brewing and make the perfect cup every time.",
      cozyTitle: "Cozy Café Await",
      cozyDesc: "Discover the best coffee spots near you for an unforgettable experience.",
      know: "Get to Know About Us",
      about: "About Kohi Coffeé",
      aboutUs: "About Us",
      relatedArticles: "𝐑𝐞𝐥𝐚𝐭𝐞𝐝 𝐀𝐫𝐭𝐢𝐜𝐥𝐞𝐬",
      aboutUsDesc: "Kohi Coffeé is a coffee shop chain in Indonesia that serves coffee, snacks, and drinks. The company was founded in 2025 by Denis, who wanted to make high-quality coffee accessible to all Indonesians. Kohi Coffeé's mission is to brew coffee while being mindful of the environment.",
      serviceTitle: "GREAT SERVICE",
      serviceDesc: "Kohi Coffeé not only delivers high-quality, well-prepared coffee but also includes exceptional customer service, characterized by friendly baristas and a welcoming atmosphere.",
      pricesTitle: "AFFORDABLE PRICE",
      checkoutPaymentMethod: "Payment Method",
      checkoutSelectPaymentMethod: "Select Payment Method",
      pricesDesc: "Tuku Coffee offers high-quality coffee at affordable prices.",
      qualityTitle: "BEST QUALITY",
      qualityDesc: "Kohi Coffeé works with local farmers to produce the best quality coffee beans.",
      freshTitle: "FRESHLY MADE AND RICH TASTE",
      orderListCustomer: "Customers",
      orderListProducts: "Products",
      orderListCreatedAt: "Created At",
      freshDesc: "Kohi Coffeé is made from freshly roasted beans that are ground and brewed, resulting in a rich flavor and complex aroma.",
      healthyTitle: "QUALITY COFFEE BEANS",
      healthyDesc: "Kohi Coffeé contains caffeine, tannins, magnesium, potassium, and various phenolic compounds, which may offer health benefits such as reducing heart disease risk.",
      flavorsTitle: "AWESOME FLAVORS",
      flavorsDesc: "The taste of Kohi Coffeé can be described in a number of ways—earthy, sweet, or smoky.",
      ContactTitle: "Contact Us",
      ContactDesc: "Get in touch with us for more information",
      ContactName: "Name",
      disco: "at",
      ContactNameLabel: "Your Name",
      ContactEmail: "Email",
      EmailLabel: "Your Email@gmail.com",
      cekCart: "Checkout",
      cekCartDesc: "Checkout Your Cart",
      ContactMessage: "Message",
      ContactMessageLabel: "Your Message",
      ContactSendMessage: "Send Message",
      ContactInfo: "Contact Information",
      ContactAddress: "Address",
      ContactPhone: "Phone",
      ContactEmailLabel: "Email",
      ContactBusinessHours: "Opening hours",
      ContactBusinessTimes: [
        { day: "Monday - Friday", time: "09:00 AM - 23:00 PM" },
        { day: "Saturday", time: "10:00 AM - 23:00 PM" },
        { day: "Sunday", time: "10:00 AM - 23:00 PM" },
      ],
    backToCart: "Back To Cart",
    shippingInfo: "Order Info",
    firstName: "First Name",
    lastName: "Last Name",
    checkoutEmail: "Email",
    checkoutPhone: "Phone Number",
    checkoutAddress: "Address",
    checkoutAddressDetail: "Address Detail",
    addressDetails: ["Apartement, Home, Benchmark, etc (opsional)"],
    checkoutAddressCity: "City",
    checkoutAddressPostalCode: "Postal Code",
    checkoutAddressCountry: "State",
    checkoutSelectCountry: "Select State",
    saveInfo: "Save this info later",
    subtotal: "Subtotal",
    shipping: "Estimated Shipping Cost",
    placeOrder: "Place Order",

    // menu language
    menu: [
      {
        id: 1,
        name: "Cappucino Espresso",
        description: "A cappuccino is a strong coffee drink made with espresso, steamed milk, and milk foam. The espresso is a concentrated coffee made by forcing hot water through finely ground coffee beans.",
      },
      {
        id: 2,
        name: "Coffee Latte",
        description: "Coffee latte mixed with steamed milk and has a thin layer of foam on top.",
      },
      {
        id: 3,
        name: "Americano",
        description: "Black coffee Americano made by brewing espresso and serving with hot or ice water.",
      },
      {
        id: 4,
        name: "Honey Coffee",
        description: "Honey Coffee processed using the honey method presents sweeter notes of fruit and can thus present a beautiful complex flavour.",
      },
      {
        id: 5,
        name: "Espresso Coffee",
        description: "Espresso Coffee is a concentrated coffee drink made by forcing hot water through finely ground coffee beans at high pressure,served in small cups.",
      },
      {
        id: 6,
        name: "V60 Coffee",
        description: "V60 coffee is coffee brewed using a V-shaped dripper that uses gravity to pour water through coffee grounds. The V60 is a pour-over method that's considered one of the best ways to make coffee.",
      },
      {
        id: 7,
        name: "Caramel Honey Latte",
        description: "Caramel honey latte is a coffee drink made with espresso, steamed milk, and a honey-caramel sauce.",
      },
      {
        id: 8,
        name: "Latte Machiato",
        description: "Latte macchiato is an espresso with milk and a spoonful of foamed milk on top.",
      },
      {
        id: 9,
        name: "Roasted Hazelnut Coffee",
        description: "Our Hazelnut flavored coffee is smooth and nutty in aroma and has a rich, warm honey flavor.",
      },
      {
        id: 10,
        name: "Hazelnut Iced Coffee",
        description: "Hazelnut iced coffee is a refreshing coffee drink that combines the nutty flavor of hazelnuts with coffee.",
      },
      {
        id: 11,
        name: "Ice Caramel Coffee",
        description: "Iced caramel coffee is a cold coffee drink that's made with espresso, milk, vanilla syrup, ice, and caramel sauce.",
      },
      {
        id: 12,
        name: "Ice Coffee Gula Aren",
        description: "Ice coffee gula aren is an traditional Indonesia iced coffee drink made with coffee, brown sugar, and milk.",
      },
      {
        id: 13,
        name: "Tubruk Coffee",
        description: "Kopi Tubruk is a typical Indonesian coffee drink made by brewing coffee powder using hot water without any filtration and no sugar.",
      },
      {
        id: 14,
        name: "Balinese Coffee",
        description: "Balinese coffee, it's a traditional coffee from Bali with its unique flavors and cultural significance, offers a delightful experience that transcends mere caffeine consumption.",
      },
      {
        id: 15,
        name: "Iced Matcha",
        description: "Matcha is a high-grade green tea ground into powdered form. The green tea powder is whisked into hot water, instead of steeped, to form a frothy drink.",
      },
      {
        id: 16,
        name: "Iced Taro",
        description: "Taro drinks are sweet, creamy, and purple beverages made with taro, a starchy root vegetable with a nutty flavor.",
      },
      {
        id: 17,
        name: "Red Velvet Chocolate",
        description: "Red velvet Chocolate has a unique flavor profile that's often described as a combination of red velvet, chocolate, and a subtle tanginess.",
      },
      {
        id: 18,
        name: "Thai Tea",
        description: "Thai tea made with black tea, condensed milk, and spices, and served iced.",
      },
      {
        id: 19,
        name: "Ice Lychee Tea",
        description: "Ice lychee tea is a sweet and refreshing drink that combines black tea with lychee fruit.",
      },
      {
        id: 20,
        name: "Lemon Tea",
        description: "Lemon tea is a drink made with tea and lemon juice or lemon slices.",
      },
      {
        id: 21,
        name: "Hot Milk Tea",
        description: "Hot milk tea is a tea drink made with milk and served hot.",
      },
      {
        id: 22,
        name: "Iced Milk Tea",
        description: "Iced milk tea is a cold drink made with tea, milk, and ice.",
      },
      {
        id: 23,
        name: "Iced Tea",
        description: "Iced tea is a cold tea beverage that can be sweetened and mixed with flavored syrups.",
      },
      {
        id: 24,
        name: "Orange Juice",
        description: "Orange juice is a sweet and tart drink made from the juice of oranges.",
      },
      {
        id: 25,
        name: "Croissant",
        description: "A croissant is a buttery, flaky pastry that originated in France. It's often eaten for breakfast or as a snack, and is often served with coffee or tea.",
      },
      {
        id: 26,
        name: "Cream Puffs Pastry",
        description: "Light and airy cream puffs, filled with thick pastry cream, fluffy whipped cream, or velvety crème légère (pastry cream lightened with whipped cream).",
      },
      {
        id: 27,
        name: "Pineapple Cake",
        description: "Pineapple Cake is a sweet traditional pastry and dessert containing butterm flour, egg, sugar, and pineapple jam or slices.",
      },
      {
        id: 28,
        name: "Tiramisu Cake",
        description: "Tiramisu Cake is an elegant and rich layered Italian dessert made with delicate ladyfinger cookies, espresso or instant espresso, mascarpone cheese, eggs, sugar, Marsala wine, rum and cocoa powders",
      },
      {
        id: 29,
        name: "Chocolate Cake",
        description: "Chocolate cake or chocolate gâteau (from French: gâteau au chocolat) is a cake flavored with melted chocolate, cocoa powder, or both. It can also have other ingredients such as fudge, vanilla creme, and other sweeteners.",
      },
      {
        id: 30,
        name: "Japanese Strawberry Cake",
        description: "Strawberry cake is a cake that uses strawberry as a primary ingredient. Strawberries may be used in the cake batter, atop the cake, and in the frosting.",
      },
      {
        id: 31,
        name: "Ramen",
        description: "Ramen is a Japanese noodle soup, with a combination of a rich flavoured broth, one of a variety of types of noodle and a selection of meats or vegetables, often topped with a boiled egg.",
      },
      {
        id: 32,
        name: "Chawanmushi Custard",
        description: "Chawanmushi is a classic Japanese savory egg custard steamed in a cup. The smooth and silky custard is seasoned with dashi stock and filled with pieces of tender chicken, kamaboko fish cake, and mushrooms.",
      },
      {
        id: 33,
        name: "Takoyaki",
        description: "Takoyaki is a Japanese snack made of flour batter and octopus that's cooked in a pan into bite-sized balls.",
      },
      {
        id: 34,
        name: "Sushi",
        description: "Sushi is traditionally made with medium-grain white rice, although it can also be prepared with brown rice or short-grain rice. It is commonly prepared with seafood, such as squid, eel, yellowtail, salmon, tuna or imitation crab meat.",
      },
      {
        id: 35,
        name: "Okonomiyaki",
        description: "Okonomiyaki is a Japanese savory pancake or omelette made with flour, cabbage, eggs, and other ingredients. It's cooked on a griddle and topped with sauce.",
      },
      {
        id: 36,
        name: "Furikake Fries",
        description: "Furikake is a Japanese seasoning made primarily of dried bonito flakes, seaweed, sesame seeds, and simple pantry spices. It's savory, slightly sweet, earthy, and nutty. It's usually sold in small packets and comes in various flavors.",
      },
    ],

    // article language
    articles: [
      {
        id: 1,
        title: "The Art of Brewing the Perfect Coffee",
        excerpt: "Exploring how sustainable practices are reshaping the fashion industry and what it means for consumers.",
        content: "Coffee is one of the most beloved beverages worldwide, with a rich history that dates back centuries. Whether you  enjoy a cup of espresso, cappuccino, or just a simple brewed cup, there's something magical about the aroma and  flavor that brings joy to so many people. In this article, we explore the art of brewing the perfect cup of coffee and what makes each brewing method unique.",
        readTime: "6 min read",
      },
      {
        id: 2,
        title: "Coffee and chronic liver disease or cancer",
        excerpt: "Discover about consume coffee that related with chronic liver for our health.",
        content: "In 2019, a literature reviewTrusted Source concluded that coffee intake is likely to reduce the risk of liver cancer.Earlier, in 2015, a cohort study of a multiethnic population in the United States suggested that depending on the dose, consuming two to three cups of coffee daily reduced the participants’ risk of developing hepatocellular carcinoma and chronic liver disease (CLD) by 38% and 46%Trusted Source, respectively.The meta-analysis from 2017Trusted Source also concluded that consuming any type of coffee appears to reduce the risk of liver cancer, nonalcoholic fatty liver disease, and cirrhosis. These findings are now bolstered by a 2021 studyTrusted Source suggesting that consuming all types of coffee may offer some protection against CLD.",
        readTime: "10 min read",
      },
      {
        id: 3,
        title: "Coffee & Obesity",
        excerpt: "Master the technique of layering clothes for both style and functionality.",
        content: "There is some evidence suggesting that consuming coffee may help people lose weight. One 2018 paperTrusted Source indicated that the more coffee the participants drank, the higher their mean reduction in weight, body mass index (BMI), and fat mass.A 2019 studyTrusted Source suggested that drinking coffee may have a modest association with weight loss, with a greater association in men than in women. However, these results have not been replicated, so they may not be definitive.Although coffee may provide some benefits in reducing obesity, it is not a substitute for eating  balanced diet and exercising often.",
        readTime: "9 min read",
      },
      {
        id: 4,
        title: "Reduce Depression and Raise Mood",
        excerpt: "Boost Your Mood with Consume Coffee",
        content: "Naturally occurring polyphenols in both caffeinated and decaffeinated coffee can act as antioxidants to reduce damaging oxidative stress and inflammation of cells. It may have neurological benefits in some people and act as an antidepressant. [13] Caffeine may affect mental states such as increasing alertness and attention, reducing anxiety, and improving mood. [14] A moderate caffeine intake of less than 6 cups of coffee per day has been associated with a lower risk of depression and suicide. However in a few cases of sensitive individuals, higher amounts of caffeine may increase anxiety, restlessness, and insomnia. Suddenly stopping caffeine intake can cause headache, fatigue, anxiety, and low mood for a few days and may persist for up to a week (Source: https://nutritionsource.hsph.harvard.edu/food-features/coffee/).",
        readTime: "11 min read",
      },
      {
        id: 5,
        title: "Nutritional value",
        excerpt: "Black coffee has few calories and contains antioxidants, vitamins, and minerals.",
        content: "One hundred milliliters (about 3.3 ounces [oz]) of regular black coffee (without milk or cream) is low in calories. That is about one typical cup of black coffee, and it only contains around 2 calories. However, adding cream or sugar will increase the calorific value.Coffee beans also contain polyphenols, which are a type of antioxidant. Antioxidants can help protect the body against free radical damage. Free radicals are a type of waste product that the body naturally produces as a result of certain processes.",
        readTime: "6 min read",
      },
      {
        id: 6,
        title: "Exposure to toxic ingredients",
        excerpt: "Exposure to toxic ingredients in coffee.",
        content: "The potential ingestion of harmful chemicals like pesticides, herbicides, mycotoxins (mold), and heavy metals that can be present in coffee beans due to farming practices, processing, or storage conditions, which can cause health issues when consumed, particularly with regular high intake; the most common toxin associated with coffee is ochratoxin A, a mycotoxin that can lead to liver and kidney damage if exposure is significant.",
        readTime: "7 min read",
      },
      {
        id: 7,
        title: "Anxiety",
        excerpt: "How caffeine affects anxiety?",
        content: "Consuming high amounts of caffeine may increase the riskTrusted Source of anxiety, especially among people with panic disorder or social anxiety disorder. Less commonly, caffeine may trigger mania and psychosis in those who are susceptible.",
        readTime: "4 min read",
      },
    ],
  },

// ========================================================================================================= 

    id: {
      home: "​𝑩𝒆𝒓𝒂𝒏𝒅𝒂​​",
      navbarMenu: "𝑴𝒆𝒏𝒖",
      aboutHero: "𝑻𝒆𝒏𝒕𝒂𝒏𝒈",
      knowCoffee: "Order kopi dan makanan anda di sini",
      contact: "𝑲𝒐𝒏𝒕𝒂𝒌",
      videoTag: "Browser Anda tidak mendukung tag video.",
      navbarArticles: "𝑨𝒓𝒕𝒊𝒌𝒆𝒍",
      readArticle: "Baca Artikel",
      orderListCreatedAt: "Dibuat Pada",
      latestArticle: "𝐀𝐫𝐭𝐢𝐤𝐞𝐥 𝐓𝐞𝐫𝐛𝐚𝐫𝐮",
      readMoreArticle: "Baca selengkapnya",
      orderListNoOrdersFound: "Belum ada pesanan ditemukan...",
      orderListGetYourOrders: "Silahkan pilih pesanan anda",
      writerArticle: "Penulis",
      orders: "𝑷𝒆𝒔𝒂𝒏𝒂𝒏",
      filterAll: "Semua Menu",
      chatWithUs: "Hubungi Kami",
      chatType: "Ketik pesanmu disini...",
      searchMenu: "Cari Menu...",
      readLessFooters: "Baca Lebih Sedikit",
      readMoreFooters: "Baca Lebih Banyak",
      menuNotFound: "Menu tidak ditemukan",
      backToMenu: "Kembali ke Menu",
      menuSortBy: "Urutkan Berdasarkan",
      menuFeatured: "Unggulan",
      menuClearFilters: "Hapus Semua Filter",
      menuApplyFilters: "Terapkan Semua Filter",
      menuNotFoundDesc: "Maaf, kami tidak dapat menemukan minuman & makanan yang Anda cari...",
      addToCart: "Tambahkan ke Keranjang",
      coverMenuDetailTitle: "Menu Rincian",
      selectStock: "Stok",
      placeHolderOrderList: "Cari berdasarkan nama atau produk...",
      orderListTitle: "Daftar Pesanan",
      orderListDelete: "Hapus",
      menuDetailTitle: "Deskripsi",
      menuDetailDesc: "Silahkan lanjutkan ke pembayaran",
      menuNameAtoZ: "Nama: A sampai Z",
      menuNameZtoA: "Nama: Z sampai A",
      menuPriceLowToHigh: "Harga: Rendah ke Tinggi",
      menuPriceHighToLow: "Harga: Tinggi ke Rendah",
      menuCategories: "Kategori",
      priceRange: "Rentang Harga",
      orderListPhone: "Nomor Handphone",
      ourMenu : "Menu Kami",
      clickMenu: "Lihat Rincian",
      menuDetailQuantity: "Kuantitas",
      viewDetails: "𝐏𝐞𝐬𝐚𝐧 𝐒𝐞𝐤𝐚𝐫𝐚𝐧𝐠",
      shareArticles: "Bagikan Artikel Ini",
      relatedArticles: "𝐀𝐫𝐭𝐢𝐤𝐞𝐥 𝐓𝐞𝐫𝐤𝐚𝐢𝐭",
      seeMenuTitle: "Hidangan Khas Kami",
      seeMenuButton: "𝐋𝐢𝐡𝐚𝐭 𝐒𝐞𝐦𝐮𝐚 𝐌𝐞𝐧𝐮 𝐊𝐡𝐚𝐬 𝐊𝐚𝐦𝐢",
      articHero: "Artikel",
      articHeroDesc: "Lihat Artikel",
      footerTitle: "𝑲𝑶𝑯𝑰 𝑪𝒐𝒇𝒇𝒆é 幸",
      footerDesc: "Kopi premium yang terbuat dari biji kopi berkualitas tinggi.",
      currentTime: "Waktu Saat ini di",
      quickLinks: "Tautan Cepat",
      discoverDesc: "𝑻𝒆𝒎𝒖𝒌𝒂𝒏", 
      discoversDescs: "𝑷𝒓𝒐𝒔𝒆𝒔𝒏𝒚𝒂",
      fitTitle: "𝑨𝒑𝒂 𝒀𝒂𝒏𝒈 𝑲𝒂𝒎𝒖 𝑫𝒂𝒑𝒂𝒕 𝑫𝒂𝒓𝒊 𝑲𝒂𝒎𝒊?",
      testimoniTitle: "Pelanggan Kami",
      testimoniNext: "Selanjutnya",
      partnerTitle: "Mitra Kami",
      footerShop: "Menu",
      coffeeTalkTitle: "𝑻𝒆𝒓𝒐𝒃𝒐𝒔𝒂𝒏 𝑩𝒖𝒅𝒂𝒚𝒂 𝑲𝒐𝒑𝒊 𝒅𝒊 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂!",
      coffeeTalkDesc: "Kohi Coffeé menghadirkan konsep dan gaya kedai kopi khas Jepang. Kami ingin mengajak semua orang, mulai dari pecinta kopi, yang suka nongkrong dan ingin dianggap sebagai pecinta kopi, hingga mereka yang bukan pecinta kopi, untuk menikmati budaya baru minum kopi yang menyenangkan.",
      coffeeTalkLoc: "Distrik Kami",
      footerAbout: "Tentang Kami",
      footerContact: "Kontak Kami",
      orderListDetails: "Rincian",
      orderListProducts: "Produk",
      footerShippingInfo: "Info Pengiriman",
      footerReturns: "Petunjuk",
      footerGuide: "Panduan",
      privacyPolicy: "Kebijakan Privasi",
      termsService: "Persyaratan Layanan",
      cookiePolicy: "Kebijakan Cookie",
      customerService: "Pelayanan Pelanggan",
      contactUs: "Hubungi Kami",
      founderKohi: "Pendiri Kohi Coffeè 幸",
      founderKohiDesc: "Hola👋, saya adalah pendiri Kohi Coffeè 幸 dengan konsep Jepang, saya seorang Web Developer, dan Digital Marketing selama lebih dari 5 tahun di industri ini.",
      backToArticles: "Kembali ke Artikel",
      articlesNotFound: "Artikel tidak ditemukan",
      copyright: "Dilindungi Hak Cipta",
      cart: "Keranjang",
      ArticleTitle: "𝐀𝐫𝐭𝐢𝐤𝐞𝐥 𝐔𝐧𝐠𝐠𝐮𝐥𝐚𝐧",
      explore: "Jelajahi Lebih Lanjut",
      shopCart: "Keranjang Belanja",
      checkCart: "Periksa Pesanan Anda",
      emptyCart: "Ups...Keranjang Pesanan Anda Kosong",
      emptyCartDesc: "Ambil Pesananmu dulu yuk..",
      emptyCartOrder: "Kosongkan Semua Keranjang",
      proceedCart: "Lanjutkan ke Pembayaran",
      continueShop: "Balik Ke Menu",  
      toggleLanguage: "Bahasa Inggris",
      discover: "Jelajahi koleksi kopi premium dan hidangan pilihan kami, diracik dengan sempurna untuk menghadirkan kenyamanan dan cita rasa terbaik...",
      order: "𝐏𝐞𝐬𝐚𝐧 𝐒𝐞𝐤𝐚𝐫𝐚𝐧𝐠",
      orderListPostalCode: "Kode Pos",
      orderListAddress: "Alamat",
      goCart: "Keranjang Belanja",
      orderSummary: "Total Pesanan",
      learnMore: "Pelajari Lebih Lanjut",
      selectVariant: "Pilih Varian",
      checkoutPaymentMethod: "Metode Pembayaran",
      checkoutSelectPaymentMethod: "Pilih Metode Pembayaran",
      selectSize: "Ukuran",
      brewTitle: "Menyeduh Seperti Barista Profesional",
      brewDesc: "Pelajari seni menyeduh kopi dan buatlah secangkir kopi yang sempurna setiap saat.",
      beanTitle: "Biji Kopi Premium",
      relatedsArticles: "Artikel Terkait",
      beanDesc: "Nikmati pilihan biji kopi terbaik dari seluruh dunia.",
      cozyTitle: "kafe yang nyaman menanti",
      orderListInvoice: "Lihat Invoice",
      cozyDesc: "Temukan kedai kopi terbaik di dekat Anda untuk pengalaman yang tak terlupakan.",
      newsletterTitle: "Bergabung dengan Newsletter Kami",
      newsletterText: "Langganan untuk mendapatkan penawaran spesial, hadiah gratis, dan pembaruan",
      emailPlaceholder: "Masukkan email Anda",
      subscribe: "Langganan",
      freeShipping: "Ongkir Gratis",
      freeShippingDesc: "Untuk pesanan di atas Rp100.000",
      comfortPlace: "Tempat Nyaman dan Estetik",
      comfortPlaceDesc: "Disajikan dengan nuansa keindahan alam Bali",
      wifi: "Wifi Gratis",
      disco: "di",
      wifiDesc: "Duduk bersantai bersama teman atau keluarga sambil internetan",
      securePayment: "Pembayaran Aman",
      securePaymentDesc: "100% pembayaran aman",
      orderListCustomer: "Pelanggan",
      orderListcloseOrders: "Tutup Order",
      orderListNoOrdersFoundHere: "disini",
      price: "Harga Terjangkau",
      priceDesc: "Kopi kami tidak terlalu mahal, cocok untuk siapa saja, ayo pesan satu",
      support24: "Dukungan 24/7",
      support24Desc: "Layanan pelanggan khusus",
      qualityProducts: "Kopi Berkualitas",
      qualityProductsDesc: "Diambil dari pilihan biji kopi terbaik",
      qualityTools: "Alat Kopi Terbaik",
      qualityToolsDesc: "Kami memberikan yang terbaik untuk pelanggan kami, menggunakan alat dengan kualitas terbaik.",
      know: "Ketahui Tentang Kami",
      about: "Tentang Kohi Coffeé",
      aboutUs: "Tentang Kami",
      aboutUsDesc: "Kohi Coffeé adalah jaringan kedai kopi di Indonesia yang menyediakan kopi, makanan ringan, dan minuman. Didirikan pada tahun 2025 oleh Denis, Kohi Coffeé bertujuan untuk menyediakan kopi berkualitas tinggi untuk semua orang.",
      serviceTitle: "PELAYANAN TERBAIK",
      serviceDesc: "Kohi Coffeé tidak hanya menyajikan kopi berkualitas tinggi tetapi juga layanan pelanggan luar biasa, dengan barista ramah dan suasana yang menyenangkan.",
      pricesTitle: "HARGA TERJANGKAU",
      pricesDesc: "Kohi Coffeé menawarkan kopi berkualitas tinggi dengan harga yang terjangkau.",
      qualityTitle: "KUALITAS TERBAIK",
      orderListviewInvoice: "Lihat Invoice",
      orderListAddOrders: "Tambah Order",
      qualityDesc: "Kohi Coffeé bekerja sama dengan petani lokal untuk menghasilkan biji kopi kualitas terbaik.",
      freshTitle: "DIBUAT SEGAR DAN RASA YANG KAYA",
      orderListPaymentChannel: "Bank Pembayaran",
      orderListPaymentMethod: "Metode Pembayaran",
      freshDesc: "Kopi Kohi dibuat dari biji kopi yang baru dipanggang, digiling, dan diseduh, memberikan aroma dan rasa yang kaya.",
      healthyTitle: "BIJI KOPI BERKUALITAS",
      healthyDesc: "Kopi Kohi mengandung kafein, tanin, magnesium, kalium, dan berbagai senyawa fenolik yang bisa mengurangi risiko penyakit jantung.",
      flavorsTitle: "RASA YANG LUAR BIASA",
      flavorsDesc: "Rasa kopi Kohi dapat digambarkan sebagai rasa tanah, manis, atau berasap.",
      ContactTitle: "Hubungi Kami",
      ContactDesc: "Hubungi kami untuk informasi lebih lanjut",
      ContactName: "Nama",
      ContactNameLabel: "Nama Anda",
      ContactEmail: "Email",
      EmailLabel: "Email Anda@gmail.com",
      cekCart: "Pembayaran",
      cekCartDesc: "Selesaikan Pembayaran Anda",
      ContactMessage: "Pesan",
      ContactMessageLabel: "Pesan Anda",
      ContactSendMessage: "Kirim Pesan",
      ContactInfo: "Informasi Kontak",
      ContactAddress: "Alamat",
      ContactPhone: "Telepon",
      ContactEmailLabel: "Email",
      ContactBusinessHours: "Jam Buka",
      ContactBusinessTimes: [
        { day: "Senin - Jumat", time: "09:00 AM - 23:00 PM" },
        { day: "Sabtu", time: "10:00 AM - 23:00 PM" },
        { day: "Minggu", time: "10:00 AM - 23:00 PM" }
      ],
        backToCart: "Kembali Ke Keranjang",
        shippingInfo: "Info Pengiriman",
        firstName: "Nama Depan",
        lastName: "Nama Belakang",
        checkoutEmail: "Email",
        checkoutPhone: "Nomor Telepon",
        checkoutAddress: "Alamat",
        checkoutAddressDetail: "Alamat Rincian",
        addressDetails: ["Apartemen, Perumahan, Patokan, dll (opsi)"],
        checkoutAddressCity: "Kota",
        checkoutAddressPostalCode: "Kode Pos",
        checkoutAddressCountry: "Negara",
        checkoutSelectCountry: "Pilih Negara",
        saveInfo: "Simpan Info Ini Lain Kali",
        subtotal: "Jumlah Keseluruhan",
        shipping: "Biaya Ongkir",
        placeOrder: "Tempat Pesanan",
         // menu language
    menu: [
      {
        id: 1,
        name: "Cappucino Espresso",
        description: "Cappuccino adalah minuman kopi kental yang dibuat dengan espresso, susu kukus, dan busa susu. Espresso adalah kopi pekat yang dibuat dengan memasukkan air panas ke dalam biji kopi yang digiling halus.",
      },
      {
        id: 2,
        name: "Coffee Latte",
        description: "Kopi latte dicampur dengan susu kukus dan memiliki lapisan busa tipis di atasnya.",
      },
      {
        id: 3,
        name: "Americano",
        description: "Kopi hitam Americano yang dibuat dengan menyeduh espresso dan disajikan dengan air panas atau es.",
      },
      {
        id: 4,
        name: "Kopi Madu",
        description: "Kopi Madu yang diolah menggunakan metode madu menghadirkan aroma buah yang lebih manis dan dapat menghadirkan cita rasa kompleks yang indah.",
      },
      {
        id: 5,
        name: "Kopi Espresso",
        description: "Kopi Espresso adalah minuman kopi pekat yang dibuat dengan mengalirkan air panas ke dalam biji kopi yang digiling halus dengan tekanan tinggi, disajikan dalam cangkir kecil.",
      },
      {
        id: 6,
        name: "Kopi V60",
        description: "Kopi V60 adalah kopi yang diseduh menggunakan dripper berbentuk V yang menggunakan gravitasi untuk menuangkan air melalui bubuk kopi. V60 adalah metode tuang yang dianggap sebagai salah satu cara terbaik untuk membuat kopi.",
      },
      {
        id: 7,
        name: "Latte Madu Karamel",
        description: "Latte Madu Karamel adalah minuman kopi yang dibuat dengan espresso, susu kukus, dan saus madu-karamel.",
      },
      {
        id: 8,
        name: "Latte Machiato",
        description: "Latte macchiato adalah espresso dengan susu dan sesendok susu berbusa di atasnya.",
      },
      {
        id: 9,
        name: "Kopi Hazelnut Panggang",
        description: "Kopi rasa Hazelnut kami memiliki aroma yang lembut dan seperti kacang serta memiliki rasa madu yang kaya dan hangat.",
      },
      {
        id: 10,
        name: "Es Kopi Hazelnut",
        description: "Es Kopi Hazelnut merupakan minuman kopi menyegarkan yang memadukan rasa kacang hazelnut dengan kopi.",
      },
      {
        id: 11,
        name: "Es Kopi Karamel",
        description: "Es Kopi Karamel adalah minuman kopi dingin yang dibuat dengan espresso, susu, sirup vanila, es, dan saus karamel.",
      },
      {
        id: 12,
        name: "Es Kopi Gula Aren",
        description: "Es Kopi Gula Aren adalah minuman kopi es tradisional Indonesia yang terbuat dari kopi, gula merah, dan susu.",
      },
      {
        id: 13,
        name: "Kopi Tubruk",
        description: "Kopi Tubruk merupakan minuman kopi khas Indonesia yang dibuat dengan cara menyeduh bubuk kopi menggunakan air panas tanpa penyaringan apa pun dan tanpa gula.",
      },
      {
        id: 14,
        name: "Kopi Bali",
        description: "Kopi Bali, kopi tradisional dari Bali dengan cita rasa unik dan makna budayanya, menawarkan pengalaman menyenangkan yang melampaui sekadar konsumsi kafein.",
      },
      {
        id: 15,
        name: "Es Matcha",
        description: "Matcha adalah teh hijau bermutu tinggi yang digiling menjadi bubuk. Bubuk teh hijau diseduh dengan air panas, bukan diseduh, untuk menghasilkan minuman berbusa.",
      },
      {
        id: 16,
        name: "Es Taro",
        description: "Minuman Taro adalah minuman manis, lembut, dan berwarna ungu yang terbuat dari talas, sayuran akar bertepung dengan rasa seperti kacang.",
      },
      {
        id: 17,
        name: "Cokelat Red Velvet",
        description: "Minuman Cokelat Red Velvet memiliki profil rasa unik yang sering digambarkan sebagai kombinasi antara Red Velvet, cokelat, dan sedikit rasa asam.",
      },
      {
        id: 18,
        name: "Teh Thai",
        description: "Teh Thai dibuat dengan teh hitam, susu kental manis, dan rempah-rempah, dan disajikan dingin.",
      },
      {
        id: 19,
        name: "Es Teh Leci",
        description: "Es teh leci merupakan minuman manis dan menyegarkan yang memadukan teh hitam dengan buah leci.",
      },
      {
        id: 20,
        name: "Teh Lemon",
        description: "Teh lemon adalah minuman yang terbuat dari teh dan jus lemon atau irisan lemon.",
      },
      {
        id: 21,
        name: "Teh Susu Panas",
        description: "Teh susu panas adalah minuman teh yang dibuat dengan susu dan disajikan panas.",
      },
      {
        id: 22,
        name: "Teh Susu Es",
        description: "Es Teh Susu adalah minuman dingin yang terbuat dari teh, susu, dan es.",
      },
      {
        id: 23,
        name: "Es Teh",
        description: "Es Teh adalah minuman teh dingin yang dapat diberi pemanis dan dicampur dengan sirup perasa.",
      },
      {
        id: 24,
        name: "Jus Jeruk",
        description: "Jus jeruk adalah minuman manis dan asam yang terbuat dari sari jeruk.",
      },
      {
        id: 25,
        name: "Croissant",
        description: "Croissant adalah kue kering bermentega dan renyah yang berasal dari Prancis. Kue ini sering disantap untuk sarapan atau sebagai camilan, dan sering disajikan dengan kopi atau teh.",
      },
      {
        id: 26,
        name: "Kue Kering Krim",
        description: "Kue Kering Krim yang ringan dan lembut, diisi dengan krim pastry yang kental, krim kocok yang lembut, atau crème légère (krim pastry yang diringankan dengan krim kocok).",
      },
      {
        id: 27,
        name: "Kue Nanas",
        description: "Kue Nanas adalah kue kering dan hidangan penutup tradisional yang manis yang mengandung mentega tepung, telur, gula, dan selai atau irisan nanas.",
      },
      {
        id: 28,
        name: "Kue Tiramisu",
        description: "Kue Tiramisu adalah hidangan penutup Italia berlapis yang elegan dan kaya, dibuat dengan kue ladyfinger yang lembut, espresso atau espresso instan, keju mascarpone, telur, gula, anggur Marsala, rum, dan bubuk kakao.",
      },
      {
        id: 29,
        name: "Kue Cokelat",
        description: "Kue cokelat atau chocolate gâteau (dari bahasa Prancis: gâteau au chocolat) adalah kue yang diberi rasa cokelat leleh, bubuk kakao, atau keduanya. Kue ini juga dapat diberi bahan lain seperti fudge, krim vanila, dan pemanis lainnya.",
      },
      {
        id: 30,
        name: "Kue Stroberi Jepang",
        description: "Kue stroberi adalah kue yang menggunakan stroberi sebagai bahan utama. Stroberi dapat digunakan dalam adonan kue, di atas kue, dan dalam lapisan gula.",
      },
      {
        id: 31,
        name: "Ramen",
        description: "Ramen adalah sup mie Jepang, dengan kombinasi kaldu beraroma kaya, salah satu dari berbagai jenis mie dan pilihan daging atau sayuran, sering kali diberi telur rebus.",
      },
      {
        id: 32,
        name: "Puding Chawanmushi",
        description: "Chawanmushi adalah puding telur gurih khas Jepang yang dikukus dalam mangkuk. Puding yang lembut dan halus ini dibumbui dengan kaldu dashi dan diisi dengan potongan ayam empuk, kue ikan kamaboko, dan jamur.",
      },
      {
        id: 33,
        name: "Takoyaki",
        description: "Takoyaki adalah camilan Jepang yang terbuat dari adonan tepung dan gurita yang dimasak dalam wajan menjadi bola-bola seukuran gigitan..",
      },
      {
        id: 34,
        name: "Sushi",
        description: "Sushi secara tradisional dibuat dengan beras putih berbiji sedang, meskipun dapat juga dibuat dengan beras merah atau beras berbiji pendek. Sushi umumnya dibuat dengan makanan laut, seperti cumi-cumi, belut, ikan ekor kuning, salmon, tuna, atau daging kepiting tiruan.",
      },
      {
        id: 35,
        name: "Okonomiyaki",
        description: "Okonomiyaki adalah pancake gurih atau telur dadar khas Jepang yang terbuat dari tepung, kubis, telur, dan bahan-bahan lainnya. Okonomiyaki dimasak di atas wajan datar dan diberi saus.",
      },
      {
        id: 36,
        name: "Kentang Goreng Furikake",
        description: "Furikake adalah bumbu dapur khas Jepang yang terbuat dari serpihan bonito kering, rumput laut, biji wijen, dan rempah-rempah dapur sederhana. Rasanya gurih, sedikit manis, beraroma tanah, dan beraroma kacang. Biasanya dijual dalam kemasan kecil dan tersedia dalam berbagai rasa.",
      },
    ],

    // article language
    articles: [
      {
        id: 1,
        title: "Seni Menyeduh Kopi Sempurna",
        excerpt: "Menjelajahi bagaimana praktik berkelanjutan membentuk kembali industri mode dan apa artinya bagi konsumen.",
        content: "Kopi merupakan salah satu minuman yang paling digemari di seluruh dunia, dengan sejarah yang kaya yang sudah ada sejak berabad-abad lalu. Baik Anda menikmati secangkir espresso, cappuccino, atau sekadar secangkir kopi yang diseduh, ada sesuatu yang ajaib tentang aroma dan rasanya yang membawa kegembiraan bagi banyak orang. Dalam artikel ini, kami akan membahas seni menyeduh secangkir kopi yang sempurna dan apa yang membuat setiap metode penyeduhan menjadi unik.",
        readTime: "Waktu baca 6 menit",
      },
      {
        id: 2,
        title: "Kopi dan penyakit hati kronis atau kanker",
        excerpt: "Temukan tentang konsumsi kopi yang berhubungan dengan hati kronis bagi kesehatan kita.",
        content: "Pada tahun 2019, sebuah tinjauan pustakaTrusted Source menyimpulkan bahwa asupan kopi kemungkinan dapat mengurangi risiko kanker hati. Sebelumnya, pada tahun 2015, sebuah studi kohort terhadap populasi multietnis di Amerika Serikat menunjukkan bahwa, tergantung pada dosisnya, mengonsumsi dua hingga tiga cangkir kopi setiap hari mengurangi risiko peserta terkena karsinoma hepatoseluler dan penyakit hati kronis (CLD) masing-masing sebesar 38% dan 46%. Meta-analisis dari tahun 2017Trusted Source juga menyimpulkan bahwa mengonsumsi jenis kopi apa pun tampaknya dapat mengurangi risiko kanker hati, penyakit hati berlemak nonalkohol, dan sirosis. Temuan ini kini didukung oleh sebuah studi tahun 2021Trusted Source yang menunjukkan bahwa mengonsumsi semua jenis kopi dapat memberikan perlindungan terhadap CLD.",
        readTime: "Waktu baca 10 menit",
      },
      {
        id: 3,
        title: "Kopi dan Obesitas",
        excerpt: "Kuasai teknik melapisi pakaian untuk gaya dan fungsionalitas.",
        content: "Ada beberapa bukti yang menunjukkan bahwa mengonsumsi kopi dapat membantu orang menurunkan berat badan. Satu makalah tahun 2018Trusted Source menunjukkan bahwa semakin banyak kopi yang diminum peserta, semakin tinggi rata-rata penurunan berat badan, indeks massa tubuh (IMT), dan massa lemak mereka. Sebuah studi tahun 2019Trusted Source menunjukkan bahwa minum kopi mungkin memiliki hubungan yang sederhana dengan penurunan berat badan, dengan hubungan yang lebih besar pada pria daripada pada wanita. Namun, hasil ini belum direplikasi, jadi mungkin tidak definitif. Meskipun kopi dapat memberikan beberapa manfaat dalam mengurangi obesitas, kopi bukanlah pengganti untuk mengonsumsi makanan seimbang dan berolahraga secara teratur.",
        readTime: "Waktu baca 9 menit",
      },
      {
        id: 4,
        title: "Mengurangi Depresi dan Meningkatkan Suasana Hati",
        excerpt: "Tingkatkan Mood Anda dengan Mengonsumsi Kopi",
        content: "Polifenol yang terdapat secara alami dalam kopi berkafein dan tanpa kafein dapat bertindak sebagai antioksidan untuk mengurangi stres oksidatif dan peradangan sel yang merusak. Polifenol mungkin memiliki manfaat neurologis pada beberapa orang dan bertindak sebagai antidepresan. [13] Kafein dapat memengaruhi kondisi mental seperti meningkatkan kewaspadaan dan perhatian, mengurangi kecemasan, dan memperbaiki suasana hati. [14] Asupan kafein dalam jumlah sedang, kurang dari 6 cangkir kopi per hari, telah dikaitkan dengan risiko depresi dan bunuh diri yang lebih rendah. Namun, dalam beberapa kasus pada individu yang sensitif, jumlah kafein yang lebih tinggi dapat meningkatkan kecemasan, kegelisahan, dan insomnia. Menghentikan asupan kafein secara tiba-tiba dapat menyebabkan sakit kepala, kelelahan, kecemasan, dan suasana hati yang buruk selama beberapa hari dan dapat bertahan hingga seminggu (Sumber: https://nutritionsource.hsph.harvard.edu/food-features/coffee/).",
        readTime: "Waktu baca 11 menit",
      },
      {
        id: 5,
        title: "Nilai Gizi",
        excerpt: "Kopi hitam memiliki sedikit kalori dan mengandung antioksidan, vitamin, dan mineral.",
        content: "Seratus mililiter (sekitar 3,3 ons [oz]) kopi hitam biasa (tanpa susu atau krim) rendah kalori. Itu sekitar satu cangkir kopi hitam biasa, dan hanya mengandung sekitar 2 kalori. Namun, menambahkan krim atau gula akan meningkatkan nilai kalorinya. Biji kopi juga mengandung polifenol, yang merupakan jenis antioksidan. Antioksidan dapat membantu melindungi tubuh dari kerusakan akibat radikal bebas. Radikal bebas adalah jenis produk limbah yang diproduksi tubuh secara alami sebagai hasil dari proses tertentu.",
        readTime: "Waktu baca 6 menit",
      },
      {
        id: 6,
        title: "Paparan bahan beracun",
        excerpt: "Paparan bahan beracun dalam kopi.",
        content: "Potensi penyerapan zat kimia berbahaya seperti pestisida, herbisida, mikotoksin (jamur), dan logam berat yang dapat hadir dalam biji kopi akibat praktik pertanian, pemrosesan, atau kondisi penyimpanan, dapat menyebabkan masalah kesehatan jika dikonsumsi, terutama jika dikonsumsi dalam jumlah banyak secara teratur. Toksin paling umum yang dikaitkan dengan kopi adalah okratoksin A, mikotoksin yang dapat menyebabkan kerusakan hati dan ginjal jika paparannya signifikan.",
        readTime: "Waktu baca 7 menit",
      },
      {
        id: 7,
        title: "Kecemasan",
        excerpt: "Bagaimana kafein memengaruhi kecemasan?",
        content: "Dengan mengkonsumsi kafein dalam jumlah banyak dapat meningkatkan risiko kecemasan, terutama di antara orang-orang dengan gangguan panik atau gangguan kecemasan sosial. Yang lebih jarang, kafein dapat memicu mania dan psikosis pada mereka yang rentan.",
        readTime: "Waktu baca 4 menit",
      },
    ],
  },
}

  return (
    <LanguageContext.Provider value={{ language, translations, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}