import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

export function LanguageProvider({ children }) {

  const storedLanguage = localStorage.getItem("appLanguage") || "en";
  const [language, setLanguage] = useState(storedLanguage);

  useEffect(() => {
    localStorage.setItem("appLanguage", language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "id" : "en"));
  };

  const translations = {
    en: {
      home: "𝑯𝒐𝒎𝒆",
      menu: "𝑴𝒆𝒏𝒖",
      aboutHero: "𝑨𝒃𝒐𝒖𝒕",
      knowCoffee: "Get Your Coffee and Cakes Here",
      contact: "𝑪𝒐𝒏𝒕𝒂𝒄𝒕",
      articles: "𝑨𝒓𝒕𝒊𝒄𝒍𝒆", 
      login: "𝑳𝒐𝒈𝒊𝒏",
      readLessFooters: "Read Less",
      readMoreFooters: "Read More",
      priceRange: "Price Range",
      menuSortBy: "Sort By",
      menuFeatured: "Featured",
      menuCategories: "Categories",
      menuClearFilters: "Clear All Filters",
      menuApplyFilters: "Apply All Filters",
      menuNameAtoZ: "Name: A to Z",
      menuNameZtoA: "Name: Z to A",
      menuNotFoundDesc: "Sorry, we couldn't find the drinks & food you were looking for...",
      menuPriceLowToHigh: "Price: Low to High",
      menuPriceHighToLow: "Price: High to Low",
      viewDetails: "Order Now",
      ourMenu : "Our Menu",
      clickMenu: "View Details",
      articHero: "Articles",
      seeMenuTitle: "Our Signature Menu",
      seeMenuButton: "𝐕𝐢𝐞𝐰 𝐀𝐥𝐥 𝐎𝐮𝐫 𝐒𝐢𝐠𝐧𝐚𝐭𝐮𝐫𝐞 𝐌𝐞𝐧𝐮",
      articHeroDesc: "See Our Articles",
      footerTitle: "𝑲𝑶𝑯𝑰 𝑪𝒐𝒇𝒇𝒆é 幸",
      footerDesc: "Premium coffee that made from high-quality beans.",
      readMoreFooter: "that are carefully sourced and prepared. It can be made from single-origin beans or blends of beans from different regions. Premium coffee is often more expensive than other coffees.",
      footerShop: "Menu",
      footerAbout: "About Us",
      footerContact: "Contact",
      currentTime: "Current Time In",
      quickLinks: "Quick Links",
      discoverDesc: "𝑫𝒊𝒔𝒄𝒐𝒗𝒆𝒓 𝑻𝒉𝒆 𝑷𝒓𝒐𝒄𝒆𝒔𝒔",
      coffeeTalkTitle: "𝑪𝒐𝒇𝒇𝒆𝒆 𝑪𝒖𝒍𝒕𝒖𝒓𝒆 𝑩𝒓𝒆𝒂𝒌𝒕𝒉𝒓𝒐𝒖𝒈𝒉 𝒊𝒏 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂!",
      coffeeTalkDesc: "Kohi Coffeé presents the concept and style of a Japanese coffee shop. We want to invite everyone from coffee lovers, those who like to hang out and want to be seen as coffee lovers, to those who are not coffee lovers to enjoy the new culture of drinking coffee that is fun.",
      coffeeTalkLoc: "Our District",
      testimoniTitle: "Our Testimonials",
      testimoniNext: "Next",
      partnerTitle: "Our Partners",
      fitTitle: "𝑾𝒉𝒂𝒕 𝑫𝒐 𝒀𝒐𝒖 𝑮𝒆𝒕 𝑭𝒓𝒐𝒎 𝑼𝒔?",
      customerService: "Customer Service",
      footerShippingInfo: "Order Info",
      footerReturns: "Advice",
      footerGuide: "Guide",
      privacyPolicy: "Privacy Policy",
      termsService: "Terms of Service",
      cookiePolicy: "Cookie Policy",
      contactUs: "Contact Us",
      copyright: "All Rights Reserved",
      cart: "Cart",
      ArticleTitle: "Featured Article",
      explore: "Explore More",
      shopCart: "Shopping Cart",
      checkCart: "Checkout Your Cart",
      emptyCart: "Oops...Your Shopping Cart is Empty",
      emptyCartDesc: "Please Grab Your Order now...",
      emptyCartOrder: "Empty All the Carts",
      proceedCart: "Proceed to Checkout",
      continueShop: "Back To Menu",
      goCart: "Shopping Cart",
      orderSummary: "Total Order",   
      toggleLanguage: "Switch to Indonesian",
      discover: "Discover our curated collection of premium coffee & cakes that combines, comfort, taste, and sustainability",
      order: "Order Now",
      learnMore: "Learn More",
      newsletterTitle: "Join Our Newsletter",
      newsletterText: "Subscribe to get special offers, free giveaways, and updates",
      emailPlaceholder: "Enter your email",
      subscribe: "Subscribe",
      freeShipping: "Free Shipping",
      freeShippingDesc: "On orders over $10",
      comfortPlace: "Comfortable Place and Aesthetic",
      comfortPlaceDesc: "Served with the nuances of Bali's natural beauty",
      wifi: "Free Wifi",
      wifiDesc: "Sit and relax with friends or family while surfing the internet",
      securePayment: "Secure Payment",
      securePaymentDesc: "100% secure payment",
      price: "Affordable Price",
      priceDesc: "Our Coffee is not so expensive, it's suitable for anyone, go grab one",
      support24: "24/7 Support",
      support24Desc: "Dedicated support",
      qualityProducts: "Quality Coffee",
      qualityProductsDesc: "Handpicked from the best selection of coffee beans",
      qualityTools: "Quality Coffee Tools",
      qualityToolsDesc: "We provide the best for our customers, the best quality tools for our customers",
      beanTitle: "Premium Coffee Beans",
      beanDesc: "Experience the finest selection of coffee beans from around the world.",
      brewTitle: "Brew Like a Pro",
      brewDesc:"Learn the art of coffee brewing and make the perfect cup every time.",
      cozyTitle: "Cozy Café Await",
      cozyDesc: "Discover the best coffee spots near you for an unforgettable experience.",
      know: "Get to Know About Us",
      about: "About Kohi Coffeé",
      aboutUs: "About Us",
      aboutUsDesc: "Kohi Coffeé is a coffee shop chain in Indonesia that serves coffee, snacks, and drinks. The company was founded in 2025 by Denis, who wanted to make high-quality coffee accessible to all Indonesians. Kohi Coffeé's mission is to brew coffee while being mindful of the environment.",
      serviceTitle: "GREAT SERVICE",
      serviceDesc: "Kohi Coffeé not only delivers high-quality, well-prepared coffee but also includes exceptional customer service, characterized by friendly baristas and a welcoming atmosphere.",
      pricesTitle: "AFFORDABLE PRICE",
      pricesDesc: "Tuku Coffee offers high-quality coffee at affordable prices.",
      qualityTitle: "BEST QUALITY",
      qualityDesc: "Kohi Coffeé works with local farmers to produce the best quality coffee beans.",
      freshTitle: "FRESHLY MADE AND RICH TASTE",
      freshDesc: "Kohi Coffeé is made from freshly roasted beans that are ground and brewed, resulting in a rich flavor and complex aroma.",
      healthyTitle: "QUALITY COFFEE BEANS",
      healthyDesc: "Kohi Coffeé contains caffeine, tannins, magnesium, potassium, and various phenolic compounds, which may offer health benefits such as reducing heart disease risk.",
      flavorsTitle: "AWESOME FLAVORS",
      flavorsDesc: "The taste of Kohi Coffeé can be described in a number of ways—earthy, sweet, or smoky.",
      ContactTitle: "Contact Us",
      ContactDesc: "Get in touch with us",
      ContactName: "Name",
      ContactNameLabel: "Your Name",
      ContactEmail: "Email",
      EmailLabel: "Your Email@gmail.com",
      cekCart: "Checkout",
      cekCartDesc: "Checkout Your Cart",
      ContactMessage: "Message",
      ContactMessageLabel: "Your Message",
      ContactSendMessage: "Send Message",
      ContactInfo: "Contact Information",
      ContactAddress: "Address",
      ContactPhone: "Phone",
      ContactEmailLabel: "Email",
      ContactBusinessHours: "Opening hours",
      ContactBusinessTimes: [
        { day: "Monday - Friday", time: "09:00 AM - 23:00 PM" },
        { day: "Saturday", time: "10:00 AM - 23:00 PM" },
        { day: "Sunday", time: "10:00 AM - 23:00 PM" },
      ],
    backToCart: "Back To Cart",
    shippingInfo: "Order Info",
    firstName: "First Name",
    lastName: "Last Name",
    checkoutEmail: "Email",
    checkoutPhone: "Phone Number",
    checkoutAddress: "Address",
    checkoutAddressDetail: "Address Detail",
    addressDetails: ["Apartement, Home, Benchmark, etc (opsional)"],
    checkoutAddressCity: "City",
    checkoutAddressPostalCode: "Postal Code",
    checkoutAddressCountry: "State",
    checkoutSelectCountry: "Select State",
    saveInfo: "Save this info later",
    subtotal: "Subtotal",
    shipping: "Estimated Shipping Cost",
    placeOrder: "Place Order",
    description: "",
  },

    id: {
      home: "​𝑩𝒆𝒓𝒂𝒏𝒅𝒂​​",
      menu: "𝑴𝒆𝒏𝒖",
      aboutHero: "𝑻𝒆𝒏𝒕𝒂𝒏𝒈",
      knowCoffee: "Lihat Menu Disini",
      contact: "𝑲𝒐𝒏𝒕𝒂𝒌",
      articles: "𝑨𝒓𝒕𝒊𝒌𝒆𝒍",
      login: "𝑴𝒂𝒔𝒖𝒌",
      readLessFooters: "Baca Lebih Sedikit",
      readMoreFooters: "Baca Lebih Banyak",
      menuSortBy: "Urutkan Berdasarkan",
      menuFeatured: "Unggulan",
      menuClearFilters: "Hapus Semua Filter",
      menuApplyFilters: "Terapkan Semua Filter",
      menuNotFoundDesc: "Maaf, kami tidak dapat menemukan minuman & makanan yang Anda cari...",
      menuNameAtoZ: "Nama: A sampai Z",
      menuNameZtoA: "Nama: Z sampai A",
      menuPriceLowToHigh: "Harga: Rendah ke Tinggi",
      menuPriceHighToLow: "Harga: Tinggi ke Rendah",
      menuCategories: "Kategori",
      priceRange: "Rentang Harga",
      ourMenu : "Menu Kami",
      clickMenu: "Lihat Detil",
      viewDetails: "Pesan Sekarang",
      seeMenuTitle: "Menu Khas Kami",
      seeMenuButton: "𝐋𝐢𝐡𝐚𝐭 𝐒𝐞𝐦𝐮𝐚 𝐌𝐞𝐧𝐮 𝐊𝐡𝐚𝐬 𝐊𝐚𝐦𝐢",
      articHero: "Artikel",
      articHeroDesc: "Lihat Artikel Kami",
      footerTitle: "𝑲𝑶𝑯𝑰 𝑪𝒐𝒇𝒇𝒆é 幸",
      footerDesc: "Kopi premium yang terbuat dari biji kopi berkualitas tinggi.",
      currentTime: "Waktu Saat ini di",
      quickLinks: "Tautan Cepat",
      discoverDesc: "𝑻𝒆𝒎𝒖𝒌𝒂𝒏 𝑷𝒓𝒐𝒔𝒆𝒔𝒏𝒚𝒂", 
      fitTitle: "𝑨𝒑𝒂 𝒀𝒂𝒏𝒈 𝑲𝒂𝒎𝒖 𝑫𝒂𝒑𝒂𝒕 𝑫𝒂𝒓𝒊 𝑲𝒂𝒎𝒊?",
      testimoniTitle: "Pelanggan Kami",
      testimoniNext: "Selanjutnya",
      partnerTitle: "Mitra Kami",
      footerShop: "Menu",
      coffeeTalkTitle: "𝑻𝒆𝒓𝒐𝒃𝒐𝒔𝒂𝒏 𝑩𝒖𝒅𝒂𝒚𝒂 𝑲𝒐𝒑𝒊 𝒅𝒊 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂!",
      coffeeTalkDesc: "Kohi Coffeé menghadirkan konsep dan gaya kedai kopi khas Jepang. Kami ingin mengajak semua orang, mulai dari pecinta kopi, yang suka nongkrong dan ingin dianggap sebagai pecinta kopi, hingga mereka yang bukan pecinta kopi, untuk menikmati budaya baru minum kopi yang menyenangkan.",
      coffeeTalkLoc: "Distrik Kami",
      footerAbout: "Tentang Kami",
      footerContact: "Kontak Kami",
      footerShippingInfo: "Info Pengiriman",
      footerReturns: "Petunjuk",
      footerGuide: "Panduan",
      privacyPolicy: "Kebijakan Privasi",
      termsService: "Persyaratan Layanan",
      cookiePolicy: "Kebijakan Cookie",
      customerService: "Pelayanan Pelanggan",
      contactUs: "Hubungi Kami",
      copyright: "Dilindungi Hak Cipta",
      cart: "Keranjang",
      ArticleTitle: "Artikel Unggulan",
      explore: "Jelajahi Lebih Lanjut",
      shopCart: "Keranjang Belanja",
      checkCart: "Periksa Keranjang Anda",
      emptyCart: "Ups...Keranjang Belanja Anda Kosong",
      emptyCartDesc: "Ambil Pesananmu dulu yuk..",
      emptyCartOrder: "Kosongkan Semua Keranjang",
      proceedCart: "Lanjutkan ke Pembayaran",
      continueShop: "Balik Ke Menu",  
      toggleLanguage: "Ubah ke Bahasa Inggris",
      discover: "Temukan koleksi kopi premium dan kue pilihan kami yang menggabungkan kenyamanan, rasa, dan keberlanjutan",
      order: "Pesan Sekarang",
      goCart: "Keranjang Belanja",
      orderSummary: "Total Pesanan",
      learnMore: "Pelajari Lebih Lanjut",
      brewTitle: "Menyeduh Seperti Barista Profesional",
      brewDesc: "Pelajari seni menyeduh kopi dan buatlah secangkir kopi yang sempurna setiap saat.",
      beanTitle: "Biji Kopi Premium",
      beanDesc: "Nikmati pilihan biji kopi terbaik dari seluruh dunia.",
      cozyTitle: "kafe yang nyaman menanti",
      cozyDesc: "Temukan kedai kopi terbaik di dekat Anda untuk pengalaman yang tak terlupakan.",
      newsletterTitle: "Bergabung dengan Newsletter Kami",
      newsletterText: "Langganan untuk mendapatkan penawaran spesial, hadiah gratis, dan pembaruan",
      emailPlaceholder: "Masukkan email Anda",
      subscribe: "Langganan",
      freeShipping: "Ongkir Gratis",
      freeShippingDesc: "Untuk pesanan di atas Rp100.000",
      comfortPlace: "Tempat Nyaman dan Estetik",
      comfortPlaceDesc: "Disajikan dengan nuansa keindahan alam Bali",
      wifi: "Wifi Gratis",
      wifiDesc: "Duduk bersantai bersama teman atau keluarga sambil internetan",
      securePayment: "Pembayaran Aman",
      securePaymentDesc: "100% pembayaran aman",
      price: "Harga Terjangkau",
      priceDesc: "Kopi kami tidak terlalu mahal, cocok untuk siapa saja, ayo pesan satu",
      support24: "Dukungan 24/7",
      support24Desc: "Layanan pelanggan khusus",
      qualityProducts: "Kopi Berkualitas",
      qualityProductsDesc: "Diambil dari pilihan biji kopi terbaik",
      qualityTools: "Alat Kopi Terbaik",
      qualityToolsDesc: "Kami memberikan yang terbaik untuk pelanggan kami, menggunakan alat dengan kualitas terbaik.",
      know: "Ketahui Tentang Kami",
      about: "Tentang Kohi Coffeé",
      aboutUs: "Tentang Kami",
      aboutUsDesc: "Kohi Coffeé adalah jaringan kedai kopi di Indonesia yang menyediakan kopi, makanan ringan, dan minuman. Didirikan pada tahun 2025 oleh Denis, Kohi Coffeé bertujuan untuk menyediakan kopi berkualitas tinggi untuk semua orang.",
      serviceTitle: "PELAYANAN TERBAIK",
      serviceDesc: "Kohi Coffeé tidak hanya menyajikan kopi berkualitas tinggi tetapi juga layanan pelanggan luar biasa, dengan barista ramah dan suasana yang menyenangkan.",
      pricesTitle: "HARGA TERJANGKAU",
      pricesDesc: "Kohi Coffeé menawarkan kopi berkualitas tinggi dengan harga yang terjangkau.",
      qualityTitle: "KUALITAS TERBAIK",
      qualityDesc: "Kohi Coffeé bekerja sama dengan petani lokal untuk menghasilkan biji kopi kualitas terbaik.",
      freshTitle: "DIBUAT SEGAR DAN RASA YANG KAYA",
      freshDesc: "Kopi Kohi dibuat dari biji kopi yang baru dipanggang, digiling, dan diseduh, memberikan aroma dan rasa yang kaya.",
      healthyTitle: "BIJI KOPI BERKUALITAS",
      healthyDesc: "Kopi Kohi mengandung kafein, tanin, magnesium, kalium, dan berbagai senyawa fenolik yang bisa mengurangi risiko penyakit jantung.",
      flavorsTitle: "RASA YANG LUAR BIASA",
      flavorsDesc: "Rasa kopi Kohi dapat digambarkan sebagai rasa tanah, manis, atau berasap.",
      ContactTitle: "Hubungi Kami",
      ContactDesc: "Hubungi kami untuk informasi lebih lanjut",
      ContactName: "Nama",
      ContactNameLabel: "Nama Anda",
      ContactEmail: "Email",
      EmailLabel: "Email Anda@gmail.com",
      cekCart: "Pembayaran",
      cekCartDesc: "Selesaikan Pembayaran Anda",
      ContactMessage: "Pesan",
      ContactMessageLabel: "Pesan Anda",
      ContactSendMessage: "Kirim Pesan",
      ContactInfo: "Informasi Kontak",
      ContactAddress: "Alamat",
      ContactPhone: "Telepon",
      ContactEmailLabel: "Email",
      ContactBusinessHours: "Jam Buka",
      ContactBusinessTimes: [
        { day: "Senin - Jumat", time: "09:00 AM - 23:00 PM" },
        { day: "Sabtu", time: "10:00 AM - 23:00 PM" },
        { day: "Minggu", time: "10:00 AM - 23:00 PM" }
      ],
        backToCart: "Kembali Ke Keranjang",
        shippingInfo: "Info Pengiriman",
        firstName: "Nama Depan",
        lastName: "Nama Belakang",
        checkoutEmail: "Email",
        checkoutPhone: "Nomor Telepon",
        checkoutAddress: "Alamat",
        checkoutAddressDetail: "Alamat Detil",
        addressDetails: ["Apartemen, Perumahan, Patokan, dll (opsi)"],
        checkoutAddressCity: "Kota",
        checkoutAddressPostalCode: "Kode Pos",
        checkoutAddressCountry: "Negara",
        checkoutSelectCountry: "Pilih Negara",
        saveInfo: "Simpan Info Ini Lain Kali",
        subtotal: "Jumlah Keseluruhan",
        shipping: "Biaya Ongkir",
        placeOrder: "Tempat Pesanan",
      },
    }

  return (
    <LanguageContext.Provider value={{ language, translations, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}