import React, { createContext, useContext, useState, useEffect } from "react";

const MenuLanguageContext = createContext();

export function MenuLanguageProvider({ children }) {
  const storedLanguage = localStorage.getItem("menuLanguage") || "en";
  const [language, setLanguage] = useState(storedLanguage);

  useEffect(() => {
    localStorage.setItem("menuLanguage", language);
  }, [language]);

const translations = {
  en: {
    MenuTitle: "Our Menu",
    notFound: "Menu not found",
    backToMenu: "Back to Menu",
    description: "Description",
    quantity: "Quantity",
    addToCart: "Add to Cart",
    menu: "Menu",
    articles: "Articles",
    items: [
      {
        id: 1,
        name: "Cappucino Espresso",
        price: 24000,
        image: "https://www.livingnorth.com/images/media/articles/food-and-drink/eat-and-drink/coffee.png?fm=pjpg&w=1000&q=95",
        category: "House Blend Coffee",
        description: "Cappucino Espresso composed with of a single, double, or triple espresso shot and hot milk.",
      },
      {
        id: 2,
        name: "Coffee Latte",
        price: 22000,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Latte_at_Doppio_Ristretto_Chiang_Mai_01.jpg/1200px-Latte_at_Doppio_Ristretto_Chiang_Mai_01.jpg",
        category: "House Blend Coffee",
        description: "Coffee latte mixed with steamed milk and has a thin layer of foam on top.",
      },
      {
        id: 3,
        name: "Americano",
        price: 20000,
        image: "https://dolo.com.au/cdn/shop/articles/522979505-shutterstock_1973536478.jpg?v=1690528484",
        category: "Arabica Coffee",
        description: "Black coffee made by brewing espresso and serving with hot or ice water.",
      },
      {
        id: 4,
        name: "Honey Coffee",
        price: 39000,
        image: "https://coffeehero.com.au/cdn/shop/articles/42c1e6ccc7c8cfeffa737fed713a7265_2048x2048.jpg?v=1630828054",
        category: "Arabica Coffee",
        description: "Honey Coffee processed using the honey method presents sweeter notes of fruit and can thus present a beautiful complex flavour.",
      },
      {
        id: 5,
        name: "Espresso Coffee",
        price: 30000,
        image: "https://asset.kompas.com/crops/_SfcFYf71wzjEp-eNLHB_subNpI=/0x0:1000x667/750x500/data/photo/2020/10/05/5f7a1e1a209d9.jpg",
        category: "Arabica Coffee",
        description: "Espresso is a concentrated coffee drink made by forcing hot water through finely ground coffee beans at high pressure, served in small cups.",
      },
      {
        id: 6,
        name: "V 60 Coffee",
        price: 48500,
        image: "https://kopi2sks.id/wp-content/uploads/2024/10/hq720.jpg",
        category: "Arabica Coffee",
        description: "Coffee made using a coffee brewing technique using a V-shaped dripper that has a 60 degree angle.",
      },
      {
        id: 7,
        name: "Caramel Honey Latte",
        price: 53000,
        image: "https://www.nespresso.com/shared_res/mos/free_html/au/b2b/recipes/images/caramel-honey-latte-coffee-recipe-menu.jpg",
        category: "House Blend Coffee",
        description: "Caramel honey latte is a coffee drink made with espresso, steamed milk, and a honey-caramel sauce.",
      },
      {
        id: 8,
        name: "Latte Machiato",
        price: 60775,
        image: "https://www.kultbohne.de/wp-content/uploads/2024/07/Macchiato-01.webp",
        category: "House Blend Coffee",
        description: "Latte macchiato is an espresso with milk and a spoonful of foamed milk on top.",
      },
      {
        id: 9,
        name: "Roasted Hazelnut Coffee",
        price: 24500,
        image: "https://data.thefeedfeed.com/static/2022/12/19/167148578963a0d95dd1a02.jpg",
        category: "Arabica Coffee",
        description: "Our Hazelnut flavored coffee is smooth and nutty in aroma and has a rich, warm honey flavor.",
      },
      {
        id: 10,
        name: "Hazelnut Iced Coffee",
        price: 150000,
        image: "https://markieskitchen.com/wp-content/uploads/2023/06/hazelnut-iced-coffee-1.jpg",
        category: "Arabica Coffee",
        description: "Hazelnut iced coffee is a refreshing coffee drink that combines the nutty flavor of hazelnuts with coffee.",
      },
      {
        id: 11,
        name: "Ice Caramel Coffee",
        price: 25000,
        image: "https://bakingmischief.com/wp-content/uploads/2022/03/iced-caramel-latte-image-feature.jpg",
        category: "House Blend Coffee",
        description: "Iced caramel coffee is a cold coffee drink that's made with espresso, milk, vanilla syrup, ice, and caramel sauce.",
      },
      {
        id: 12,
        name: "Ice Coffee Gula Aren",
        price: 20000,
        image: "https://img.kurio.network/IYmxbqmyTfs0cHrBndzmKCdqXeo=/320x320/filters:quality(80)/https://kurio-img.kurioapps.com/21/07/06/e0f921c0-97fe-48d6-84ba-60d131b605e9.jpe",
        category: "Traditional Coffee",
        description: "Ice coffee gula aren is an traditional Indonesia iced coffee drink made with coffee, brown sugar, and milk.",
      },
      {
        id: 13,
        name: "Kopi Tubruk",
        price: 13000,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRhzqgPGg9_iQMzxlUBom-t67z1b41YyjyaMW0GLyTR6cSy3t45PgInJTph6fsJEpVTtcxuPHEH42NC6AjLYMZz4RWdgl66znUZXAd0hU",
        category: "Traditional Coffee",
        description: "Kopi Tubruk is a typical Indonesian coffee drink made by brewing coffee powder using hot water without any filtration and no sugar.",
      },
      {
        id: 14,
        name: "Balinese Coffee",
        price: 15000,
        image: "https://specialtycoffee.id/wp-content/uploads/elementor/thumbs/brewing-balinese-coffee-qvnejqmjlomj0finig7cwnpd3ssyb47aiho5nd5b0g.webp",
        category: "Traditional Coffee",
        description: "Brewing balinese coffee, with its unique flavors and cultural significance, offers a delightful experience that transcends mere caffeine consumption.",
      },
      {
        id: 15,
        name: "Iced Matcha",
        price: 23000,
        image: "https://cdn.loveandlemons.com/wp-content/uploads/2023/06/iced-matcha-latte.jpg",
        category: "Non Coffee",
        description: "Matcha is a high-grade green tea ground into powdered form. The green tea powder is whisked into hot water, instead of steeped, to form a frothy drink.",
      },
      {
        id: 16,
        name: "Iced Tarro",
        price: 23500,
        image: "https://www.shutterstock.com/image-photo/taro-milk-ice-es-tranparent-600nw-2473002405.jpg",
        category: "Non Coffee",
        description: "Taro drinks are sweet, creamy, and purple beverages made with taro, a starchy root vegetable with a nutty flavor.",
      },
      {
        id: 17,
        name: "Red Velvet Hot Chocolate",
        price: 27000,
        image: "https://househunk.com/wp-content/uploads/2024/01/Homemade-Red-Velvet-Hot-Chocolate-Mix-500x500.png",
        category: "Non Coffee",
        description: "Red velvet Chocolate has a unique flavor profile that's often described as a combination of red velvet, chocolate, and a subtle tanginess.",
      },
      {
        id: 18,
        name: "Thai Tea",
        price: 23000,
        image: "https://sakiproducts.com/cdn/shop/articles/20230310181037-thai-tea-recipe_1920x1080.webp?v=1678471844",
        category: "Non Coffee",
        description: "Thai tea typically made with black tea, condensed milk, and spices, and served iced.",
      },
      {
        id: 19,
        name: "Ice Lychee Tea",
        price: 28182,
        image: "https://dcostseafood.id/wp-content/uploads/2021/12/LYCHEE-TEA.jpg",
        category: "Non Coffee",
        description: "Ice lychee tea is a sweet and refreshing drink that combines black tea with lychee fruit.",
      },
      {
        id: 20,
        name: "Lemon Tea",
        price: 14500,
        image: "https://teacultureoftheworld.com/cdn/shop/files/Image1_1200x1200.jpg?v=1699359685",
        category: "Non Coffee",
        description: "Lemon tea is a drink made with tea and lemon juice or lemon slices.",
      },
      {
        id: 21,
        name: "Hot Milk Tea",
        price: 18500,
        image: "https://www.teaforturmeric.com/wp-content/uploads/2021/11/Masala-Chai-Tea-Recipe-Card-500x500.jpg",
        category: "Non Coffee",
        description: "Hot milk tea is a tea drink made with milk and served hot.",
      },
      {
        id: 22,
        name: "Iced Milk Tea",
        price: 13500,
        image: "https://png.pngtree.com/background/20240213/original/pngtree-ice-milk-tea-fresh-milk-tea-style-photo-picture-image_7681282.jpg",
        category: "Non Coffee",
        description: "Iced milk tea is a cold drink made with tea, milk, and ice.",
      },
      {
        id: 23,
        name: "Iced Tea",
        price: 12500,
        image: "https://bakingamoment.com/wp-content/uploads/2024/05/IMG_3367-iced-tea-500x500.jpg",
        category: "Non Coffee",
        description: "Iced tea is a cold tea beverage that can be sweetened and mixed with flavored syrups.",
      },
      {
        id: 24,
        name: "Orange Juice",
        price: 12500,
        image: "https://greenletes.com/wp-content/uploads/2018/05/orange-juice-1024x1024.png",
        category: "Non Coffee",
        description: "Orange juice is a sweet and tart drink made from the juice of oranges.",
      },
    ],
  },
  id: {
    MenuTitle: "Menu Kami",
    notFound: "Menu tidak ditemukan",
    backToMenu: "Kembali ke Menu",
    description: "Deskripsi",
    quantity: "Jumlah",
    addToCart: "Tambah ke Keranjang",
    menu: "Menu",
    articles: "Artikel",
    items: [
      {
        id: 1,
        name: "Cappucino Espresso",
        price: 24000,
        image: "https://www.livingnorth.com/images/media/articles/food-and-drink/eat-and-drink/coffee.png?fm=pjpg&w=1000&q=95",
        category: "House Blend Coffee",
        description: "Cappucino Espresso adalah kopi yang terdiri dari satu, dua, atau tiga tembakan espresso dan susu panas.",
      },
      {
        id: 2,
        name: "Kopi Latte",
        price: 22000,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Latte_at_Doppio_Ristretto_Chiang_Mai_01.jpg/1200px-Latte_at_Doppio_Ristretto_Chiang_Mai_01.jpg",
        category: "House Blend Coffee",
        description: "Kopi latte dicampur dengan susu panas dan lapisan tipis foam di atasnya.",
      },
      {
        id: 3,
        name: "Americano",
        price: 20000,
        image: "https://dolo.com.au/cdn/shop/articles/522979505-shutterstock_1973536478.jpg?v=1690528484",
        category: "Arabica Coffee",
        description: "Kopi Americano adalah kopi hitam khas amerika yang diseduh dengan espresso dan disajikan dengan air panas atau es.",
      },
      {
        id: 4,
        name: "Kopi Madu",
        price: 39000,
        image: "https://coffeehero.com.au/cdn/shop/articles/42c1e6ccc7c8cfeffa737fed713a7265_2048x2048.jpg?v=1630828054",
        category: "Arabica Coffee",
        description: "Kopi Madu yang diproses menggunakan metode honey dapat menghasilkan rasa buah yang lebih manis dan memberi pengalaman rasa yang kompleks.",
      },
      {
        id: 5,
        name: "Kopi Espresso",
        price: 30000,
        image: "https://asset.kompas.com/crops/_SfcFYf71wzjEp-eNLHB_subNpI=/0x0:1000x667/750x500/data/photo/2020/10/05/5f7a1e1a209d9.jpg",
        category: "Arabica Coffee",
        description: "Kopi Espresso adalah minuman kopi kental yang dibuat dengan memaksa air panas melalui biji kopi yang digiling halus, disajikan dalam cangkir kecil.",
      },
      {
        id: 6,
        name: "V 60 Kopi",
        price: 48500,
        image: "https://kopi2sks.id/wp-content/uploads/2024/10/hq720.jpg",
        category: "Arabica Coffee",
        description: "Kopi V 60 dibuat dengan teknik penyeduhan kopi dengan menggunakan alat dripper berbentuk V yang memiliki sudut 60 derajat",
      },
      {
        id: 7,
        name: "Latte Madu Karamel",
        price: 53000,
        image: "https://www.nespresso.com/shared_res/mos/free_html/au/b2b/recipes/images/caramel-honey-latte-coffee-recipe-menu.jpg",
        category: "House Blend Coffee",
        description: "Latte Madu Karamel adalah minuman kopi yang terbuat dari espresso, susu yang dipanaskan, dan saus karamel madu.",
      },
      {
        id: 8,
        name: "Latte Machiato",
        price: 60775,
        image: "https://www.kultbohne.de/wp-content/uploads/2024/07/Macchiato-01.webp",
        category: "House Blend Coffee",
        description: "Latte macchiato adalah espresso dengan susu dan sesendok susu busa di atasnya.",
      },
      {
        id: 9,
        name: "Kopi Hazelnut Panas",
        price: 24500,
        image: "https://data.thefeedfeed.com/static/2022/12/19/167148578963a0d95dd1a02.jpg",
        category: "Arabica Coffee",
        description: "Kopi Hazelnut Panas memiliki aroma yang halus dan kaya rasa madu yang hangat.",
      },
      {
        id: 10,
        name: "Es Kopi Hazelnut",
        price: 150000,
        image: "https://markieskitchen.com/wp-content/uploads/2023/06/hazelnut-iced-coffee-1.jpg",
        category: "Arabica Coffee",
        description: "Es Kopi Hazelnut adalah minuman kopi yang menyegarkan dengan rasa kacang hazelnut.",
      },
      {
        id: 11,
        name: "Es Kopi Karamel",
        price: 25000,
        image: "https://bakingmischief.com/wp-content/uploads/2022/03/iced-caramel-latte-image-feature.jpg",
        category: "House Blend Coffee",
        description: "Es Kopi Karamel adalah minuman kopi dingin yang terbuat dari espresso, susu, sirup vanila, es, dan saus karamel.",
      },
      {
        id: 12,
        name: "Es Kopi Gula Aren",
        price: 20000,
        image: "https://img.kurio.network/IYmxbqmyTfs0cHrBndzmKCdqXeo=/320x320/filters:quality(80)/https://kurio-img.kurioapps.com/21/07/06/e0f921c0-97fe-48d6-84ba-60d131b605e9.jpe",
        category: "Traditional Coffee",
        description: "Es kopi gula aren adalah minuman kopi es tradisional Indonesia yang terbuat dari kopi, gula merah, dan susu.",
      },
      {
        id: 13,
        name: "Kopi Tubruk",
        price: 13000,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRhzqgPGg9_iQMzxlUBom-t67z1b41YyjyaMW0GLyTR6cSy3t45PgInJTph6fsJEpVTtcxuPHEH42NC6AjLYMZz4RWdgl66znUZXAd0hU",
        category: "Traditional Coffee",
        description: "Kopi Tubruk adalah minuman kopi khas Indonesia yang diseduh menggunakan bubuk kopi panas tanpa penyaringan dan tanpa gula.",
      },
      {
        id: 14,
        name: "Kopi Bali",
        price: 15000,
        image: "https://specialtycoffee.id/wp-content/uploads/elementor/thumbs/brewing-balinese-coffee-qvnejqmjlomj0finig7cwnpd3ssyb47aiho5nd5b0g.webp",
        category: "Traditional Coffee",
        description: "Menyeduh kopi Bali dengan rasa yang unik dan kaya akan makna budaya memberikan pengalaman yang menyenangkan.",
      },
      {
        id: 15,
        name: "Es Matcha",
        price: 23000,
        image: "https://cdn.loveandlemons.com/wp-content/uploads/2023/06/iced-matcha-latte.jpg",
        category: "Non Coffee",
        description: "Es Matcha adalah teh hijau kelas tinggi yang digiling halus menjadi bubuk. Bubuk teh hijau ini dikocok dengan air panas untuk menghasilkan minuman berbusa dan disajikan dengan dingin.",
      },
      {
        id: 16,
        name: "Es Taro",
        price: 23500,
        image: "https://www.shutterstock.com/image-photo/taro-milk-ice-es-tranparent-600nw-2473002405.jpg",
        category: "Non Coffee",
        description: "Minuman Es Taro adalah minuman paling populer karena rasanya yang manis dan krimi yang terbuat dari umbi taro yang memiliki rasa kacang.",
      },
      {
        id: 17,
        name: "Cokelat Panas Red Velvet",
        price: 27000,
        image: "https://househunk.com/wp-content/uploads/2024/01/Homemade-Red-Velvet-Hot-Chocolate-Mix-500x500.png",
        category: "Non Coffee",
        description: "Cokelat Panas Red Velvet memiliki profil rasa unik yang sering digambarkan sebagai kombinasi antara red velvet, coklat, dan rasa asam yang halus.",
      },
      {
        id: 18,
        name: "Teh Thai",
        price: 23000,
        image: "https://sakiproducts.com/cdn/shop/articles/20230310181037-thai-tea-recipe_1920x1080.webp?v=1678471844",
        category: "Non Coffee",
        description: "Teh Thai adalah minuman teh hitam dengan susu kental manis dan rempah-rempah, yang disajikan dingin.",
      },
      {
        id: 19,
        name: "Teh Leci Es",
        price: 28182,
        image: "https://dcostseafood.id/wp-content/uploads/2021/12/LYCHEE-TEA.jpg",
        category: "Non Coffee",
        description: "Teh Leci Es adalah minuman teh manis dan segar yang terbuat dari jus buah leci yang dikombinasikan dengan teh.",
      }, 
      {
        id: 20,
        name: "Teh Lemon",
        price: 14500,
        image: "https://teacultureoftheworld.com/cdn/shop/files/Image1_1200x1200.jpg?v=1699359685",
        category: "Non Coffee",
        description: "Teh lemon adalah minuman yang terbuat dari teh dan jus lemon atau irisan lemon.",
      },
      {
        id: 21,
        name: "Teh Susu Panas",
        price: 18500,
        image: "https://www.teaforturmeric.com/wp-content/uploads/2021/11/Masala-Chai-Tea-Recipe-Card-500x500.jpg",
        category: "Non Coffee",
        description: "Teh susu panas adalah minuman teh yang dibuat dengan susu dan disajikan panas.",
      },
      {
        id: 22,
        name: "Teh Susu Dingin",
        price: 13500,
        image: "https://png.pngtree.com/background/20240213/original/pngtree-ice-milk-tea-fresh-milk-tea-style-photo-picture-image_7681282.jpg",
        category: "Non Coffee",
        description: "Teh susu dingin adalah minuman dingin yang terbuat dari teh, susu, dan es.",
      },
      {
        id: 23,
        name: "Teh Dingin",
        price: 12500,
        image: "https://bakingamoment.com/wp-content/uploads/2024/05/IMG_3367-iced-tea-500x500.jpg",
        category: "Non Coffee",
        description: "Teh dingin adalah minuman teh dingin yang dapat diberi pemanis dan dicampur dengan sirup perasa.",
      },
      {
        id: 24,
        name: "Jus jeruk",
        price: 12500,
        image: "https://greenletes.com/wp-content/uploads/2018/05/orange-juice-1024x1024.png",
        category: "Non Coffee",
        description: "Jus jeruk adalah minuman manis dan asam yang terbuat dari sari jeruk.",
      },
    ]
  }
}
const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "id" : "en"));
  };

return (
    <MenuLanguageContext.Provider value={{ language, translations, toggleLanguage }}>
      {children}
    </MenuLanguageContext.Provider>
  );
}

// Custom hook to use the menu language context
export function useMenuLanguage() {
  return useContext(MenuLanguageContext);
}
